cabal-version: 3.0
name: moorhen
version: 0.1.0.0
license: MPL-2.0
license-file: LICENCE
maintainer: voxelmagpie@mailbox.org
author: VoxelMagpie
tested-with: ghc ==9.12.4 || ==9.10.3
synopsis:
  Functional language with imperative control flow, immutable data, and effects tracking

category: Language
build-type: Simple
extra-doc-files: README.md

executable moorhen
  main-is: Main.hs
  build-tool-depends: alex:alex
  hs-source-dirs: app
  other-modules:
    Back.MirToJs
    CmdLine
    Driver
    Embed
    Error
    Front.Ast
    Front.AstPp
    Front.Hir
    Front.HirFns
    Front.Lexer
    Front.LexPost
    Front.Macros
    Front.Parser
    Front.Tc.Context
    Front.Tc.Error
    Front.Tc.Expr
    Front.Tc.Generics
    Front.Tc.Inputs
    Front.Tc.Names
    Front.Tc.Patterns
    Front.Tc.PType
    Front.Tc.Show
    Front.Tc.State
    Front.Tc.StateImpl
    Front.Tc.Tc
    Front.Tc.Traits
    Front.Tc.Types
    Front.Tc.VDef
    Front.Tokens
    Front.TypeKind
    MhPrelude
    Mid.HirToMir
    Mid.Mir
    Mid.MirPp
    Mid.Optimiser
    Names
    SrcLoc
    Strings
    Tests
    Timings
    TypeString
    Vars

  default-language: GHC2021
  default-extensions:
    DeriveAnyClass
    DerivingStrategies
    DuplicateRecordFields
    FunctionalDependencies
    LambdaCase
    NoFieldSelectors
    NoImplicitPrelude
    OverloadedRecordDot
    OverloadedStrings
    RecordWildCards
    StrictData
    TypeFamilies

  ghc-options:
    -Wall
    -Wunused-packages
    -rtsopts=all
    -threaded

  build-depends:
    array,
    async,
    base,
    bytestring,
    data-default,
    directory,
    file-embed,
    filepath,
    hashable,
    hashtables,
    mtl,
    newtype-generics,
    text,
    time,
    unordered-containers,
    vector,
